name: CI Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    if: github.actor != 'dependabot[bot]' # Prevent any dependency updates
    runs-on: ubuntu-latest
    name: Validate Build
    env:
      solution-path: './src/NetCoreUtilities.UnitTesting.sln'
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      with:
        fetch-depth: 0

    - name: Ensure .NET Installed
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
      with:
        dotnet-version: 9.0.x
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@7417b1089e2c7de93510f1901d656ddf60bb024f # v4.7.0
      with:
        versionSpec: '6.4.0'
  
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@7417b1089e2c7de93510f1901d656ddf60bb024f # v4.7.0
      
    - name: Restore Packages
      run: dotnet restore "${{ env.solution-path }}"
    - name: Build
      run: dotnet build "${{ env.solution-path }}" --no-restore --configuration Release -p:version=${{ steps.gitversion.outputs.majorMinorPatch }}
